import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { TheHeader } from '@/components/TheHeader/TheHeader';
import React from 'react';
import { ThemeProvider } from '@/services/ThemeContext';
import StoreProvider from '@/services/StoreProvider';
import Search from '@/components/Search/Search';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const setInitialTheme = `
    (function() {
      function getInitialTheme() {
        const savedTheme = window.localStorage.getItem('theme');
        return savedTheme || 'light';
      }
      document.documentElement.setAttribute('data-theme', getInitialTheme());
    })();
  `;

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <script dangerouslySetInnerHTML={{ __html: setInitialTheme }} />
        <StoreProvider>
          <ThemeProvider>
            <TheHeader />
            <Search />
            <main className={'container'}>{children}</main>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
